server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          locator:
            enabled: false
            lowerCaseServiceId: true
          routes:
            - id: auth
              uri: ${AUTH_MS_URL:http://localhost:8081}
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1
            - id: test
              uri: ${TEST_MS_URL:http://localhost:8082}
              predicates:
                - Path=/test/**
              filters:
                - StripPrefix=1
            - id: scheduling
              uri: ${SCHEDULING_MS_URL:http://localhost:2003}
              predicates:
                - Path=/scheduling/**
              filters:
                - StripPrefix=1

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE
    com:
      netflix:
        discovery: TRACE
