server:
  port: 8081

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          locator:
            enabled: true
            lowerCaseServiceId: true
          routes:
            - id: auth
              uri: lb://auth
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1
            - id: test
              uri: lb://test
              predicates:
                - Path=/test/**
              filters:
                - StripPrefix=1
#    client:
#      hostname: localhost

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: ${SERVICE_REGISTRY_URL:http://localhost:8761/eureka/}

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE
    com:
      netflix:
        discovery: TRACE
