server:
  port: 8082

spring:
  application:
    name: test

  cloud:
    client:
      hostname: localhost

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: ${SERVICE_REGISTRY_URL:http://localhost:8761/eureka/}

jwt:
  public.key: classpath:app.pub