CREATE TABLE IF NOT EXISTS schedulings (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
patient_id   BIGINT NOT NULL,
doctor_id    BIGINT NOT NULL,
start_at     TIMESTAMPTZ NOT NULL,
end_at       TIMESTAMPTZ NOT NULL,
status       VARCHAR(20) NOT NULL CHECK (status IN ('SCHEDULED','COMPLETED','CANCELLED','NO_SHOW','RESCHEDULED')),
created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);