server:
  port: 2003

spring:
  application:
    name: scheduling

  cloud:
    client:
      hostname: localhost

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://tc3-scheduling-postgres:5432/tech-challenge-03-scheduling}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.time_zone: UTC
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:rabbitmq}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:user}
    password: ${SPRING_RABBITMQ_PASSWORD:123456}
app:
  services:
    auth: ${AUTH_MS_URL:http://localhost:8081}
    history: ${HISTORY_MS_URL:http://localhost:2002/graphql}

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: ${SERVICE_REGISTRY_URL:http://localhost:8761/eureka/}

jwt:
  public.key: classpath:app.pub